version: '3'
services:
  cassandra-node1:
    image: cassandra:latest
    environment:
      - CASSANDRA_SEEDS=cassandra-node1
      - CASSANDRA_CLUSTER_NAME=MyCassandraCluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
    ports:
      - "9042:9042"
  cassandra-node2:
    image: cassandra:latest
    environment:
      - CASSANDRA_SEEDS=cassandra-node2
      - CASSANDRA_CLUSTER_NAME=MyCassandraCluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
    ports:
      - "9043:9042"